# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1061, 659)
        MainWindow.setStyleSheet("background-color: #14213D")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(160, 0, 901, 661))
        self.stackedWidget.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.stackedWidget.setObjectName("stackedWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.stackedWidget.addWidget(self.Home)
        self.Lecturers = QtWidgets.QWidget()
        self.Lecturers.setObjectName("Lecturers")
        self.stackedWidget.addWidget(self.Lecturers)
        self.Staff = QtWidgets.QWidget()
        self.Staff.setObjectName("Staff")
        self.stackedWidget.addWidget(self.Staff)
        self.homeButton = QtWidgets.QPushButton(self.centralwidget)
        self.homeButton.setGeometry(QtCore.QRect(20, 40, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.homeButton.setFont(font)
        self.homeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.homeButton.setStyleSheet("QPushButton{\n"
"\n"
"    color: #e5e5e5;\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    \n"
"}")
        self.homeButton.setObjectName("homeButton")
        self.Lecturerbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Lecturerbtn.setGeometry(QtCore.QRect(20, 90, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.Lecturerbtn.setFont(font)
        self.Lecturerbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Lecturerbtn.setObjectName("Lecturerbtn")
        self.Staffbtn = QtWidgets.QPushButton(self.centralwidget)
        self.Staffbtn.setGeometry(QtCore.QRect(20, 140, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.Staffbtn.setFont(font)
        self.Staffbtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Staffbtn.setObjectName("Staffbtn")
        self.Staffbtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Staffbtn_2.setGeometry(QtCore.QRect(20, 190, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.Staffbtn_2.setFont(font)
        self.Staffbtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Staffbtn_2.setObjectName("Staffbtn_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.homeButton.setText(_translate("MainWindow", "Home"))
        self.Lecturerbtn.setText(_translate("MainWindow", "Lecturers"))
        self.Staffbtn.setText(_translate("MainWindow", "Other Staff"))
        self.Staffbtn_2.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
